name: linux_vim

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - PROFILE=.profile VIM=vim    TAG=latest
          - PROFILE=.profile VIM=vim    TAG=v8.0.0107
          - PROFILE=.profile VIM=vim    TAG=v8.1.0000
          - PROFILE=.profile VIM=vim    TAG=v8.1.2000
          - PROFILE=.profile VIM=neovim TAG=latest
          - PROFILE=.profile VIM=neovim TAG=v0.3.0
          - PROFILE=.profile VIM=neovim TAG=v0.4.0
          - PROFILE=.profile VIM=neovim TAG=v0.4.2
    steps:
      - uses: actions/checkout@v2
      - name: setup
        shell: bash
        run: |
          docker --vesion
          make VIM=${VIM} TAG=${TAG} image
      - name: Run tests
        shell: bash
        run: |
          make VIM=${VIM} TAG=${TAG} ARGS="-e PROFILE=${PROFILE} -e CI=docker" test
          make VIM=${VIM} TAG=${TAG} helptags
